services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql_uniqlo_t3h'
    environment:
      - 'MYSQL_DATABASE=uniqlo_t3h_database'
      - 'MYSQL_ROOT_PASSWORD=admin123'
    ports:
      - '3306:3306'
